[workspace]
resolver = "2"

members = ["cargo-work", "horsed", "stable"]

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1.83"
clap = { version = "4.5.23", features = ["cargo", "derive"] }
russh = "0.49.2"
russh-keys = "0.49.2"
stable = { path = "./stable" }
shell-escape = "0.1.5"
ssh-key = "0.6.7"
tokio = { version = "1.42", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
