[workspace]
resolver = "2"

members = ["cargo-work", "horsed", "stable"]

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1.83"
clap = { version = "4.5.23", features = ["cargo", "derive"] }
russh = "0.49.2"
russh-keys = "0.49.2"
stable = { path = "./stable" }
shell-escape = "0.1.5"
ssh-key = "0.6.7"
futures = "0.3.31"
tokio = { version = "1.42", features = ["full", "tracing"] }
parking_lot = "0.12.3"
once_cell = { version = "1.20.2", features = ["parking_lot"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
git2 = { version = "0.19", features = ["zlib-ng-compat"] }
